// client/src/components/application/console/ConsoleContent.svelte
<script lang="ts">
    import TopNavigation from "../../top/TopNavigation.svelte";
    import {Check, Icon} from "svelte-hero-icons";

    let messages = ["Test1", "Test2"]

    function sendCommand() {
        // @ts-ignore
        let message: string = document.getElementById("console-input").value;
        // @ts-ignore
        document.getElementById("console-input").value = "";

        messages = [...messages, message];
    }
</script>

<div class="content-container">
    <TopNavigation title={"Console"}/>
    <div class="content-list">
        <div class="console">
            {#each messages as message}
                <div class="console-line">{message}</div>
            {/each}
        </div>
    </div>
    <form class="bottom-bar" on:submit={function(event) {event.preventDefault();sendCommand();}}>
        <input type="text" id="console-input" placeholder="Enter command..." class="bottom-bar-input" />
        <div on:click={function() {sendCommand();}}>
            <Icon src="{Check}" size="26" class="text-green-500 mx-2 dark:text-primary cursor-pointer"/>
        </div>
    </form>
</div>

// client/src/components/content/ConsoleContent.jsx
import TopNavigation from '../sidebar/TopNavigation';
import { BiSend } from 'react-icons/bi';

const ServerContent = ( { messages, clickSend } ) => {
    return (
        <div className='content-container'>
            <TopNavigation title={"Console"}/>
                <div className='content-list'>
                    <div className="console">
                        {
                            messages.map(message => {
                                return (
                                    <ConsoleMessage text={message}/>
                                );
                            })
                        }
                    </div>
                </div>
            <BottomBar clickSend={clickSend} />
        </div>
  );
};

const BottomBar = ( { clickSend } ) => (
  <form className='bottom-bar' onSubmit={event => {
      event.preventDefault();
      clickSend();
  }}>
      <input type='text' id="console-input" placeholder='Enter command...' className='bottom-bar-input' />
      <SendIcon clickSend={clickSend} />
  </form>
);

const ConsoleMessage = ({ text }) => {
  return (
      <div className="console-line">{text}</div>
  );
};

const SendIcon = ( {clickSend} ) => {
    return (
        <div onClick={clickSend}>
            <BiSend
                size='22'
                className='text-green-500 mx-2 dark:text-primary cursor-pointer'
            />
        </div>
    );
};

export default ServerContent;
