// client/src/components/top/TopNavigation.svelte
<script lang="ts">
    import {Icon, Moon, Sun, Hashtag, UserCircle} from "svelte-hero-icons";
    import {onMount} from "svelte";

    import {darkMode} from "../../js/Store";

    export let title: string;

    onMount(() => {
        darkMode.update(value => {
            update(value);
            return value;
        })
    });

    function changeTheme() {
        darkMode.update(value => {
            update(!value)

            return !value
        })
    }

    function update(value: boolean) {
        const bodyClass = window.document.body.classList;

        value ? bodyClass.add("dark") : bodyClass.remove("dark");
    }

</script>

<div class="top-navigation">
    <p class='title-text-root'>WebControl</p>
    <Icon src={Hashtag} size="18" class="mr-1 ml-1 title-slash" />
    <h5 class='title-text'>{title}</h5>
    <span on:click={changeTheme}>
        {#if $darkMode}
            <Icon src={Sun} class="top-navigation-icon" size="24" />
        {:else}
            <Icon src={Moon} class="top-navigation-icon" size="24" />
        {/if}
    </span>
    <Icon src={UserCircle} size="24" class="top-navigation-icon" />
</div>

// client/src/components/sidebar/TopNavigation.jsx
import { FaUserCircle, FaMoon, FaSun } from 'react-icons/fa';
import { CgFormatSlash } from 'react-icons/cg';
import useDarkMode from '../../hooks/useDarkMode';

const TopNavigation = ( { title } ) => {
  return (
    <div className='top-navigation'>
        <Title title={title}/>
        <ThemeIcon />
        <UserCircle />
    </div>
  );
};

const ThemeIcon = () => {
  const [darkTheme, setDarkTheme] = useDarkMode();
  const handleMode = () => setDarkTheme(!darkTheme);
  return (
    <span onClick={handleMode}>
      {darkTheme ? (
        <FaSun size='24' className='top-navigation-icon' />
      ) : (
        <FaMoon size='24' className='top-navigation-icon' />
      )}
    </span>
  );
};

const UserCircle = () => <FaUserCircle size='24' className='top-navigation-icon' />;
const SlashIcon = () => <CgFormatSlash size='28' className='title-slash' />;
const Title = ({ title }) => {
    return (
        <>
            <p className='title-text-root'>WebControl</p>
            <SlashIcon />
            <h5 className='title-text'>{title}</h5>
        </>
    );
};

export default TopNavigation;
